#!/bin/bash
apt-get update -y
apt-get install -y apache2 php php-curl libapache2-mod-php php-mysql jq

# --- Make Apache serve index.php before index.html at the root URL ---
echo "DirectoryIndex index.php index.html" | sudo tee /etc/apache2/mods-enabled/dir.conf

# --- Install and enable SSL support ---
apt-get install -y openssl
a2enmod ssl

# --- Write the cert and key generated by Terraform ---
mkdir -p /etc/ssl/certs /etc/ssl/private
cat <<EOF > /etc/ssl/certs/apache-selfsigned.crt
${cert_pem}
EOF

cat <<EOF > /etc/ssl/private/apache-selfsigned.key
${private_key_pem}
EOF

chmod 600 /etc/ssl/private/apache-selfsigned.key

# --- Point Apache's default SSL site at the cert/key ---
sed -i 's|SSLCertificateFile.*|SSLCertificateFile /etc/ssl/certs/apache-selfsigned.crt|' /etc/apache2/sites-available/default-ssl.conf
sed -i 's|SSLCertificateKeyFile.*|SSLCertificateKeyFile /etc/ssl/private/apache-selfsigned.key|' /etc/apache2/sites-available/default-ssl.conf

a2ensite default-ssl
systemctl restart apache2

# --- Existing setup below ---
usermod -a -G azureuser azureuser

mkdir -p /var/www/html
chown -R azureuser:azureuser /var/www
chmod 2775 /var/www
find /var/www -type d -exec chmod 2775 {} \;
find /var/www -type f -exec chmod 0664 {} \;
cd /var/www/html
curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq > index.html
sed -i '1i<pre>' index.html
sed -i '$a</pre>' index.html
echo "OK" > health   # creates a dedicated health-check endpoint so the LB probe (request_path = "/health") gets a response
curl https://raw.githubusercontent.com/Azure/vm-scale-sets/master/terraform/terraform-tutorial/app/index.php -O